gpt-4o:
  OPENAI_API_BASE: 
  OPENAI_API_KEY: 
  OPENAI_API_MODEL: "gpt-4o"
  MAX_TOKENS: 300
  TEMPERATURE: 0.0
  REQUEST_INTERVAL: 10
gpt-4v:
  OPENAI_API_BASE: 
  OPENAI_API_KEY: "sk-"
  OPENAI_API_MODEL: "gpt-4v"
  MAX_TOKENS: 300
  TEMPERATURE: 0.0
  REQUEST_INTERVAL: 10
gpt-4v-1:
  OPENAI_API_BASE: 
  OPENAI_API_KEY: "sk-"
  OPENAI_API_MODEL: "gpt-4v"
  MAX_TOKENS: 300
  TEMPERATURE: 0.0
  REQUEST_INTERVAL: 10